<?php

namespace MarketingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EntryPointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryPointRepository extends EntityRepository
{
    /**
     * @param array $filters
     * @return \Doctrine\ORM\Query
     */
    public function findByCustomFilters(array $filters)
    {
        $queryBuilder = $this->createQueryBuilder('ep');

        if (!empty($filters['status'])) {
            $queryBuilder
                ->andWhere('ep.status = :status')
                ->setParameter('status', $filters['status']);
        }

        return $queryBuilder->getQuery();
    }
}
