<?php

namespace MarketingBundle\Repository;

/**
 * EntryPointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryPointRepository extends \Doctrine\ORM\EntityRepository
{
}
