<?php

namespace MarketingBundle\Repository;

/**
 * LeadProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeadProviderRepository extends \Doctrine\ORM\EntityRepository
{
}
