<?php

namespace MarketingBundle\Repository;

/**
 * LeadTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeadTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
