<?php

namespace MarketingBundle\Repository;

/**
 * ObjectiveMarketingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectiveMarketingRepository extends \Doctrine\ORM\EntityRepository
{
}
