<?php

namespace MarketingBundle\Repository;

/**
 * UserRegistrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRegistrationRepository extends \Doctrine\ORM\EntityRepository
{
}
