imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_sqlite
        path:     %database_path%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

hautelook_alice:
    locale: 'fr_FR'
    seed: 1

fos_elastica:
    clients:
        default:
            host: localhost
            port: 9200
    indexes:
        marketing:
            types:
                offer_funding:
                    persistence:
                        listener:
                            insert: false
                            update: false
                            delete: false
                            enabled: false
                            flush: false
        test_marketing:
            client: default
            types:
                test_offer_funding:
                    properties:
                        id:
                            type: integer
                        type:
                            type: string
                        modelId:
                            type: integer
                        rangeId:
                            type: integer
                        price:
                            type: string
                        start_date:
                            type: date
                        end_date:
                            type: date
                        details:
                            type: string
                        legalNotice:
                            type: string
                        visual:
                            type: string
                        name:
                            type: string
                    persistence:
                        driver: orm
                        model: OfferBundle\Entity\OfferFunding
                        finder: ~
                        provider: ~
                        listener: ~
                        repository: OfferBundle\Repository\Elastica\OfferFundingRepository