# configuration file for elastic search
fos_elastica:
    clients:
        default:
            host: localhost
            port: 9200
    indexes:
        marketing:
            client: default
            index_name: '%marketing_index_name%'
            types:
                offer_funding:
                    properties:
                        id:
                            type: integer
                        type:
                            type: string
                        modelId:
                            type: integer
                        rangeId:
                            type: integer
                        price:
                            type: string
                        start_date:
                            type: date
                        end_date:
                            type: date
                        details:
                            type: string
                        legalNotice:
                            type: string
                        visual:
                            type: string
                        name:
                            type: string
                    persistence:
                        driver: orm
                        model: OfferBundle\Entity\OfferFunding
                        finder: ~
                        provider: ~
                        listener: ~
                        repository: OfferBundle\Repository\Elastica\OfferFundingRepository

                marketing_objective:
                    properties:
                        id:
                            type: integer
                        status:
                            type: string
                        name:
                            type: string
                        legacyId:
                            type: string
                        createdAt:
                            type: date
                        updatedAt:
                            type: date
                    persistence:
                        driver: orm
                        model: MarketingBundle\Entity\MarketingObjective
                        finder: ~
                        provider: ~
                        listener: ~
                        repository: MarketingBundle\Repository\Elastica\MarketingObjectiveRepository