# configuration file for elastic search
fos_elastica:
    clients:
        default:
            host: localhost
            port: 9200
    indexes:
        marketing:
            client: default
            index_name: '%marketing_index_name%_%env%'
            types:
                offer_funding:
                    properties:
                        id:
                            type: integer
                        type:
                            type: string
                        modelId:
                            type: integer
                        rangeId:
                            type: integer
                        price:
                            type: string
                        start_date:
                            type: date
                        end_date:
                            type: date
                        details:
                            type: string
                        legalNotice:
                            type: string
                        visual:
                            type: string
                        name:
                            type: string
                    persistence:
                        driver: orm
                        model: OfferBundle\Entity\OfferFunding
                        finder: ~
                        provider: ~
                        listener: ~
                        repository: OfferBundle\Repository\Elastica\OfferFundingRepository

                marketing_objective:
                    properties:
                        id:
                            type: integer
                        status:
                            type: string
                        name:
                            type: string
                        legacyId:
                            type: string
                        createdAt:
                            type: date
                        updatedAt:
                            type: date
                    persistence:
                        driver: orm
                        model: MarketingBundle\Entity\MarketingObjective
                        finder: ~
                        provider: ~
                        listener: ~
                        repository: MarketingBundle\Repository\Elastica\MarketingObjectiveRepository

                contact_form:
                    properties:
                        id:
                            type: integer
                        legacyId:
                            type: string
                        name:
                            type: string
                        description:
                            type: text
                        createProspectAccount:
                            type: boolean
                        trackingCodeInit:
                            type: text
                        trackingCodeValidation:
                            type: text
                        sendEmailToCrm:
                            type: boolean
                        sendEmailToCdv:
                            type: boolean
                        campaignEvent:
                            type: object
                            properties:
                                name:
                                    type: string
                                status:
                                    type: string
                                legacyId:
                                    type: string
                                description:
                                    type: text
                                waitingList:
                                    type: boolean
                                descriptionEvent:
                                    type: text
                                descriptionTarget:
                                    type: text
                                startDate:
                                    type: date
                                endDate:
                                    type: date
                                eventType:
                                    type: object
                                    properties:
                                        legacyId:
                                            type: string
                                        name:
                                            type: string
                                        status:
                                            type: string
                        subscription:
                            type: object
                            properties:
                                name:
                                    type: string
                                status:
                                    type: string
                                legacyId:
                                    type: string
                        entryPoint:
                            type: object
                            properties:
                                name:
                                    type: string
                                status:
                                    type: string
                                legacyId:
                                    type: string
                        leadProvider:
                            type: object
                            properties:
                                name:
                                    type: string
                                status:
                                    type: string
                                legacyId:
                                    type: string
                        contactFormType:
                            type: object
                            properties:
                                name:
                                    type: string
                                status:
                                    type: string
                                legacyId:
                                    type: string
                        createdAt:
                            type: date
                        updatedAt:
                            type: date
                    persistence:
                        driver: orm
                        model: MarketingBundle\Entity\ContactForm
                        finder: ~
                        provider: ~
                        listener: ~
                        repository: MarketingBundle\Repository\Elastica\ContactFormRepository
