parameters:
    crud_exchange: '%env%.CRUD'
    dlx_name: '%env%.dead-letter'
    dlq_name: '%env%.dead-letter'
    scoring_queue: '%env%.scoring.crud'
    scoring_routing_key: '%env%.scoring.crud'

# RabbitMQ configuration
old_sound_rabbit_mq:
    connections:
        default:
            host:     '%rabbitmq_host%'
            port:     5672
            user:     '%rabbitmq_user%'
            password: '%rabbitmq_password%'
            vhost:    '/'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0

            #requires php_sockets.dll
            #use_socket: true # default false
        another:
            # A different (unused) connection defined by an URL. One can omit all parts,
            # except the scheme (amqp:). If both segment in the URL and a key value (see above)
            # are given the value from the URL takes precedence.
            # See https://www.rabbitmq.com/uri-spec.html on how to encode values.
            url: 'amqp://%rabbitmq_user%:%rabbitmq_password%@%rabbitmq_host%/vhost?lazy=1&connection_timeout=6'

    consumers:
        scoring_crud:
            connection: 'default'
            exchange_options:
                name: '%crud_exchange%'
                type: 'direct'
            queue_options:
                name: '%scoring_queue%'
                routing_keys:
                  - '%scoring_routing_key%'
                arguments:
                    'x-dead-letter-exchange': ['S', '%dlx_name%']
                    'x-dead-letter-routing-key': ['S', '%scoring_queue%']
            callback: MarketingBundle\Service\AMQP\Consumer\ScoringConsumer

        dead_messages:
            connection: default
            exchange_options: {name: '%dlx_name%', type: direct}
            queue_options:
                name: '%dlq_name%'
                routing_keys:
                    - '%scoring_queue%'
            callback: Mullenlowe\CommonBundle\Component\AMQP\DeadLetterConsumer

    producers:
        marketing_crud:
            connection: 'default'
            class: Mullenlowe\CommonBundle\Component\AMQP\CrudProducer
            exchange_options:
                name: '%crud_exchange%'
                type: 'direct'

mullenlowe_common:
    rabbitmq_crud_publisher:
        producer: 'old_sound_rabbit_mq.marketing_crud_producer'
        mapping:
            - { context: 'ContactForm',                     routing_key: 'crud.marketing.contactForm' }
            - { context: 'MarketingPermission',             routing_key: 'crud.marketing.marketingPermission' }
            - { context: 'MyaudiUserInterest',              routing_key: 'crud.marketing.myaudiUserInterest' }
            - { context: 'MyaudiUserMarketingObjective',    routing_key: 'crud.marketing.myaudiUserMarketingObjective' }
            - { context: 'Score',                           routing_key: 'crud.marketing.score' }
            - { context: 'OfferAftersale',                  routing_key: 'crud.marketing.offerAftersale' }
            - { context: 'OfferSale',                       routing_key: 'crud.marketing.offerSale' }
            - { context: 'MyaudiUserInvitation',            routing_key: 'crud.marketing.myaudiUserInvitation' }
