services:
    MarketingBundle\ETL\Transformer\UserPreTransformer:
        public: true
        calls:
            -
                method: setConnection
                arguments:
                    - '@doctrine.dbal.user_connection'
