<?php

namespace OfferBundle\Repository;

/**
 * OfferAftersaleMyaudiUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferAftersaleMyaudiUserRepository extends \Doctrine\ORM\EntityRepository
{
}
