<?php

namespace OfferBundle\Repository;

/**
 * OfferFormTypeNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferFormTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
