<?php

namespace OfferBundle\Repository;

/**
 * OfferSaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferSaleRepository extends \Doctrine\ORM\EntityRepository
{
}
