<?php

namespace OfferBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OfferTermsTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferTermsTemplateRepository extends EntityRepository
{
}
