<?php

namespace OfferBundle\Repository;

/**
 * SubtypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferSubtypeRepository extends \Doctrine\ORM\EntityRepository
{
}
