<?php

namespace OfferBundle\Repository;

/**
 * OfferSaleMyaudiUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferSaleMyaudiUserRepository extends \Doctrine\ORM\EntityRepository
{
}
