<?php

namespace OfferBundle\Repository;

/**
 * OfferNewCarTermsPropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferNewCarTermsPropertyRepository extends \Doctrine\ORM\EntityRepository
{
}
