<?php

namespace OfferBundle\Repository;

/**
 * OfferAftersaleTermsPropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferAftersaleTermsPropertyRepository extends \Doctrine\ORM\EntityRepository
{
}
