<?php

namespace OfferBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OfferAftersaleMyaudiUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferAftersaleMyaudiUserRepository extends EntityRepository
{
}
