<?php

namespace OfferBundle\Repository;

/**
 * OfferAftersaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferAftersaleRepository extends \Doctrine\ORM\EntityRepository
{
}
