<?php

namespace OfferBundle\Repository;

/**
 * OfferSecondhandCarTermsPropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferSecondhandCarTermsPropertyRepository extends \Doctrine\ORM\EntityRepository
{
}
